collections:
    devopsma:
      output: true
    prozenics:
      output: true
    agilencr2020:
      output: true


 
defaults:
  - 
    scope: 
      path: ""
      type: agilencr2020
    values: 
      issuedBy: Ajay Kabra
      issuedInstitute: Agile NCR
      dateOfIssue: 29 November 2020
      program: AgileNCR20
      advCTAName: Listen Now
      advCTALink: https://youtu.be/ZwPNe2vWXfE
      CTAText: Listen, Share and Subscribe to AgileCast
      advBGImagelink: https://certifyme.online/img/cert/agilencr2020/banner.jpeg 
      brandLogo: https://certifyme.online/img/cert/agilencr2020/logo.jpg
      brandMessage: AgileCast ,India's premiere podcast on Agile led technologies. Sharing knowledge is in Xebia's DNA and staying true to this value, practitioners from XACT (Xebia Agile Consulting and Transformation) share their experience and knowledge on current and trending topics related to Agile on AgileCast. A podcast dedicated to science and practice of Agile
      contactPh_number: +31 (0)35 538 1921
      contactEmail: info@xebia.com
      contactCompanyWebSiteLink: www.xebia.com
      text: This certificate is issued for part participating  AgileNCR 2020 . This year's theme for the conference was HUMANIZING BUSINESS INNOVATION. Agile Manifesto always emphasized individuals & interactions and we all know that when people are adaptive, then the organization is adaptive too. Humans are the biggest contributors in bringing Business Agility and in this remote working year and new normal, it is people and their innovative ideas that would drive organizations and their businesses to sustain and shine.  


# Site settings
title: Certify Me  
email: info@quadralogics.com
description: Your trusted Assessment and Certification Platform
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
company: QuadraLogics
#Heading 
Head1: Certify Me.Online 
Head2: Your Trusted Digital Certificate Publishing Platform
Head3: We add more value to your Training & Certifications 
HeadCTA: Request a Demo
HeadCTALink: mailto:info@quadralogics.com?subject = Express Interest&body = I  would like to know more about how certifyme.online could add value to my  Training & Certifications.
#Call to action
USPH: Certify Me.Online Advantage
USP: Certify me is a digital certificate publishing platform for training companies. The sharable, mobile-friendly, and personalized certificate pages enables training firms to gain better visibility, branding, and lead generation via organic sharing across different social media platforms like Facebook, Linkedin, Instagram, etc. Organic sharing is naturally triggered when trainees want to showcase her achievements in her network circle. Each organic share on an average generates 1000+ impressions thus leading to more visibility & sales leads. <br/> Certifyme.online is a QuadraLogics concern .

TContentH: Download Training Contents
TContentB: Topics include Docker, Kubernetes, Jenkins, Puppet, Ansible, Chef, Terraform, AWS Cloud formation, Nagios, Git, & InSpec
TContentLink: https://drive.google.com/u/0/uc?id=1jIOXTEolfSOy2nYpC1QxoVlfX_xn5Fns&export=download

#services
ServicesHeading:  Enhanced Lead Generation Just 4 Steps Away

Services1H: Step 1.  OnBoard 
Services1: This one-time step is to ensure you understand how you could benefit from our product. While onboarding we also ensure all brands and firms associated with us are genuine and authorized firms.
Services2H: Step 2. Issue
Services2: Once Onboarded you can issue your certificate to your student on your certificate template along with our unique QR code that can be used to verify the certificate at any given time and place. 

Services3H: Step 3. Review
Services3: The issued Certificate and branding collaterals undergo a quick quality check to ensure your certificates pages are error-free and presentable. Afterall your brand value is also our concern.

Services4H:  Step 4. Publish
Services4: Once published you can share it with your students and relax. Each shared certificate on an average generates 1000+ impressions thus leading to more sales leads and more branding.

#features 

FeatureHeading:  Adding more value

Feature1H:  Publish Digitized Certificates  
Feature1: Add value to your conference & workshop by publishing Digitized Certificates to your speakers and delegates. These online certificates of recognition act's as a digital souvenir .

Feature2H: Gain More Visibility
Feature2: Our certificates can easily be shared across many social media platforms and as a conference/training organizers this enables  you to drive in more visibility to your program 

Feature3H:  Drive More leads 
Feature3: Our certificates are customizable to add your branding like a banner, a call to action, etc. This feature enables you to utilizes it for marketing your own product / services .

Feature4H: Verifiable Certificates   
Feature4: Each of our certificates is enabled with a QR code to establish authenticity seamlessly. This also ensures our certificates can not be forged. 
#Clinets
clinetsH : Sample Cetificate WebPage

#Portfolio

portfolioHeader : Learn from the Expert!
portfolioHeaderA: Help us help you
portfolioHeaderLink: https://www.youtube.com/embed/i2Vh6yUiZn4
portfolioHeaderB : About your trainer 
portfolioHeaderBN: Anju M Dominic
portfolioHeaderB1: Founder | Speaker | Author
portfolioHeaderB1C: Anju M Dominic is a well accredited professional corporate trainer and consultant in the field of DevOps . She has conducted over 70+ hands-on workshops across different product and service companies. She is also a trainer/author across various training companies including PluralSight, Edureka, KnowledgeHut, etc. She is currently the Principal consultant and founder of QuadraLogics, a boutique training/consulting firm. Anju is well known for her contributions to technical articles which includes two books and several whitepapers in the field of software engineering. She is also a regular speaker for many DevOps and Agile conferences.
#Ribbon 
RHead1: Get Certified Now
RHead2: 
RHead3: 
RCTA:  Enroll !

ph_number: +91-6362315334
github_username: linkedin/company/quadralogics

footer: ©  2020  www.quadralogics.com , certifyme.online is a QuadraLogics concern 



# Build settings
markdown: kramdown


