collections:
    devopsma:
      output: true
    prozenics:
      output: true
    agilencr2020:
      output: true
    samples:
      output: true
    ATAGTR2020:
      output: true
    AACONF:
      output: true
    EDU:
      output: true
    RSGK:
      output: true
    


 
defaults:
  - 
    scope: 
      path: ""
      type: agilencr2020
    values: 
      issuedBy: Agile NCR 2020 Program Committee
      issuedInstitute: www.agilencr.org
      dateOfIssue: 29 November 2020
      program: AgileNCR 2020
      advCTAName: Listen Now
      advCTALink: https://youtu.be/ZwPNe2vWXfE
      CTAText: Listen, Share and Subscribe to AgileCast
      advBGImagelink: https://certifyme.online/img/cert/agilencr2020/banner.jpeg 
      brandLogo: https://certifyme.online/img/cert/agilencr2020/logo.jpg
      brandMessage: AgileCast ,India's premiere podcast on Agile led technologies. Sharing knowledge is in Xebia's DNA and staying true to this value, practitioners from XACT (Xebia Agile Consulting and Transformation) share their experience and knowledge on current and trending topics related to Agile on AgileCast. A podcast dedicated to science and practice of Agile
      contactPh_number: +31 (0)35 538 1921
      contactEmail: info@xebia.com
      contactCompanyWebSiteLink: www.xebia.com
      text: This certificate is issued for participating in AgileNCR 2020 conference. AgileNCR is an annual Agile software development conference organized by Xebia and Agile enthusiasts of the NCR region.

  - 
    scope: 
      path: ""
      type: devopsma
    values: 
      issuedBy: Anju M Dominic
      issuedInstitute: QUADRALOGICS
      dateOfIssue: 19 October 2020
      program: DevOps Master Architect
      advCTAName: Enrol Now
      advCTALink: https://quadralogics.com/training/DevOpsMasterArchitect.html
      CTAText: Learn hands-on DevOps with QUADRALOGICS
      advBGImagelink: https://certifyme.online/img/certificate/devopsma/DMW1.png
      brandLogo: https://certifyme.online/img/certificate/devopsma/logo.png
      brandMessage: QUADRALOGICS ,India's premier DevXOps Training & Consulting Firm. We enable you with the technical know how to adopt DevOps in it's true essence that too in a hands-on way. 
      contactPh_number: +91-6362315334
      contactEmail: info@quadralogics.com
      contactCompanyWebSiteLink: www.quadralogics.com
      text: This certificate is issued to recognise the participant for successfully completing all the requirements for the DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months. 
  
  - 
    scope: 
      path: "_devopsma/Ansible"
      type: devopsma
    values: 
      program: Ansible module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Ansible Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.    
  - 
    scope: 
      path: "_devopsma/Puppet"
      type: devopsma
    values: 
      program: Puppet module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Puppet Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/InSpec"
      type: devopsma
    values: 
      program: InSpec module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the InSpec Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/Nagios"
      type: devopsma
    values: 
      program: Nagios module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Nagios Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/Kubernetes"
      type: devopsma
    values: 
      program: Kubernetes module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Kubernetes Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/CloudFormation"
      type: devopsma
    values: 
      program: CloudFormation module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the CloudFormation Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/Terraform"
      type: devopsma
    values: 
      program: Terraform module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Terraform Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  - 
    scope: 
      path: "_devopsma/Chef"
      type: devopsma
    values: 
      program: Chef module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Chef Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.    
  - 
    scope: 
      path: "_devopsma/Docker"
      type: devopsma
    values: 
      program: Docker module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Docker Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.
  
  - 
    scope: 
      path: "_devopsma/Jenkins"
      type: devopsma
    values: 
      program: Jenkins module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Jenkins Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.

  - 
    scope: 
      path: "_devopsma/Git"
      type: devopsma
    values: 
      program: Git module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the Git Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.    
  
  - 
    scope: 
      path: "_devopsma/CloudFormation"
      type: devopsma
    values: 
      program: CloudFormation module in DevOps Master Architect Workshop
      text: This badge is issued to recognise the awardee for successfully completing all the requirements for the CloudFormation Module in DevOps Master Architect Workshop, a comprehensive programme spanning 72 hrs/ 3 months.

  - 
    scope: 
      path: "" 
      type: ATAGTR2020
    values: 
      issuedBy: "#ATAGTR2020 Program Committee"
      issuedInstitute: Agile Testing Alliance
      dateOfIssue: 28-Oct-2020
      program: "#ATAGTR2020 - Global Testing Retreat"
      advCTAName: Know more
      advCTALink: https://gtr.agiletestingalliance.org/
      CTAText: "Be a part of #ATAGTR2020, Register Now"
      advBGImagelink: https://certifyme.online/img/cert/sample/baner.jpg
      brandLogo: https://certifyme.online/img/cert/sample/logo.png
      brandMessage: "#ATAGTR2020 Global Testing Conference is back again in its 5th edition with more fun and more learnings. Be a part of #ATAGTR2020"
      contactPh_number: +91 8433919049
      contactEmail: ATAsupport@AgileTestingAlliance.org
      contactCompanyWebSiteLink: nul
      text: "#ATAGTR2020 Global Testing Conference is back again in its 5th edition with more fun and more learnings. Conference is scheduled for 12th and 13th December 2020. We have 2 full days with minimum 3 parallel tracks on both the days. 60+ speakers more than 40 Interactive sessions and Talks and Live Labs."
      certificatePath: https://certifyme.online/img/cert/sample/atrBadge.png
  - 
    scope: 
      path: "_ATAGTR2020/volunteer" 
      type: ATAGTR2020
    values: 
      certificatePath: https://certifyme.online/img/cert/badge/ATA_vol_Badge.png

  - 
    scope: 
      path: "" 
      type: AACONF
    values: 
      issuedBy: Sam Zawadi
      issuedInstitute: Agnostic Agile
      dateOfIssue: 20-Nov-2020
      program: "AACONF 2020 (Agnostic Agile Conference 2020)"
      advCTAName: Register Now
      advCTALink: https://agnosticagile.org/
      CTAText: "Be a part of #AAConf"
      advBGImagelink: https://certifyme.online/img/cert/badge/AAConf2020BadgeBanner.jpg
      brandLogo: https://agnosticagile.org/imgs/Logo@2x.png
      brandMessage: "Join #AAConf, a global, online conference that will run through Asia Pacific, EMEA and the Americas"
      contactPh_number: nul
      contactEmail: hello@agnosticagile.org
      contactCompanyWebSiteLink: nul
      text: "Although times may be uncertain, one thing will remain true - there is power among people and there is power in an Agnostic Agile Mindset.
      Agnostic Agile is launching #AAConf, a global, online conference that will run through Asia Pacific, EMEA and the Americas. The theme for #AAConf 2020 is Business Agility."
      certificatePath: https://certifyme.online/img/cert/badge/AAConf2020Badge.png
  - 
    scope: 
      path: ""
      type: EDU
    values: 
      issuedBy: Program Committee
      

  - 
    scope: 
      path: "_EDU/SRM/IEC20"
      type: EDU
    values: 
      issuedBy: Rohit, Agarwal
      issuedInstitute: SRM Indian Energy Conference
      dateOfIssue: 20-Nov-2020
      program: SRM IEC 2020
      advCTAName: Learn More
      advCTALink: https://certifyme.online/
      CTAText: Drive 10X more relevant traffic to your events page 
      advBGImagelink: https://certifyme.online/img/whyCM.png
      brandLogo: https://certifyme.online/img/logo.png
      brandMessage: Certify Me is a "Trusted Digital Certificate Publishing Platform" . We empower large event producers to generate and publish digitized certificates/Badges for conferences, sports events, training, etc . Our mobile-friendly , verifiable , social-media complaint certificate web pages enable event visibility and reach.
      contactPh_number: +91-8334011404
      contactEmail: iecsrm@gmail.com
      contactCompanyWebSiteLink: www.srmiec.co.in
      text: SRM Indian Energy Conference is a platform that works on the principles and guidlines of a Model United Nations. The 5th edition of SRMIEC will be conducted on the 20th-22nd November 2020 to involve, evolve and aggregate the ideas of the youth. A conference that exists to assist you in voicing your opinions to the world. A stage that provides you with the opportunity to meet like-minded individuals who have the passion to formulate actions towards a better and healthier future. SRM IEC is a conference where policies envisaging an efficient future are going to be drafted, a place where the foundations for a brighter tomorrow will be laid.
      certificatePath: https://certifyme.online/EDU/SRM/IEC20/SRM.jpeg

  - 
    scope: 
      path:  ""
      type: RSGK
    values: 
      issuedBy: Arijit Sarbagna
      issuedInstitute: Agile of East
      dateOfIssue: 01-Nov-2020
      program: Regional Scrum Gathering℠ Kolkata
      advCTAName: Register Now
      advCTALink: https://www.townscript.com/e/rsg-kolkata-2020
      CTAText: Join us at Regional Scrum Gathering Kolkata 2021
      advBGImagelink: https://certifyme.online/img/cert/RSGK/Banner.jpg
      brandLogo: https://certifyme.online/img/cert/RSGK/logo.png
      brandMessage: Regional Scrum Gathering Kolkata 2021
      contactPh_number: nul
      contactEmail: nul
      contactCompanyWebSiteLink: https://rsgkol.zoneconnect.in/
      text: Regional Scrum Gatherings℠ is an opportunity to connect with like-minded agile and Scrum practitioners, trainers, coaches, and enthusiasts. Hear amazing keynote speakers, participate in Coaching Clinics, CSP Lounges, Networking Sessions and more. And one also earns Scrum Education Units (SEUs) for attending. Regional Scrum Gatherings℠ are organized and hosted by local/regional agilists, so each one is truly a unique and valuable experience! And we are thankful to our distinguished speakers - who have kindly agreed to share their valuable time and experience with the event participants. This certificate/badge is a small token of appreciation towards their kind gesture.
    

# Site settings
title: Certify Me  
email: info@quadralogics.com
description: Your trusted Assessment and Certification Platform
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
company: QuadraLogics
#Heading 
Head1: Certify Me.Online 
Head2: Your Trusted Digital Certificate Publishing Platform
Head3: We add more value to your Training & Certifications 
HeadCTA: Request a Demo
HeadCTALink: mailto:info@quadralogics.com?subject = Express Interest&body = I  would like to know more about how certifyme.online could add value to my  Training & Certifications.
#Call to action
USPH: Certify Me.Online Advantage
USP: Certify Me is a "Trusted Digital Certificate Publishing Platform" . We empower large event producers to generate and publish digitized certificates/Badges for conferences, sports events, training, etc . Our mobile-friendly , verifiable , social-media complaint certificate web pages enable event visibility and reach. <br/> Certifyme.online is a QuadraLogics concern.

TContentH: Download Training Contents
TContentB: Topics include Docker, Kubernetes, Jenkins, Puppet, Ansible, Chef, Terraform, AWS Cloud formation, Nagios, Git, & InSpec
TContentLink: https://drive.google.com/u/0/uc?id=1jIOXTEolfSOy2nYpC1QxoVlfX_xn5Fns&export=download

#services
ServicesHeading:  How does it work?

Services1H: Step 1.  Upload  Names 
Services1: The names of awardees are to be uploaded along with a certification template. We understand your data privacy concerns hence you don't need to upload any sensitive data including email etc. 

Services2H: Step 2.  Generate Certificates 
Services2: certifyme will help you generate the certificates as a webpage for each awardee. Each certificate is stored in a unique web address with a QRcode embedded on it for verifiability 

Services3H: Step 3. Issue Certificates 
Services3: Sit back & relax as our application automates the mundane task of certificate authoring & publication. The generated certificate web pages are mobile/social media-friendly and sharable

#features 

FeatureHeading:  Adding more value

Feature1H:   Digitized Certificates & Badges
Feature1: Gain more traction to your conferences & events by publishing Digitized Certificate/Badges webpage to your speakers/delegates. These online certificates of recognition act as a digital souvenir.

Feature2H: Gain More Visibility
Feature2: The sharable credentials enable you drive 10X more relevant traffic to your events page over paid advertisements. It also generates a ton of social media engagements boosting your event's visibility.

Feature3H:  Un-lock advertising space 
Feature3: Our certificate web pages are customizable to include a branding banner, CTA, etc. Utilize this space to market your product/ services or sell this ad space to your lead sponsorer.

Feature4H: Verifiable Certificates   
Feature4: Each of our certificates is enabled with a QR code to establish authenticity seamlessly. This also ensures our certificates can not be forged. We also have email-based manual verification 
#Clinets
clinetsH : Sample Cetificate WebPage

#Portfolio


#Ribbon 
RHead1: Get Certified Now
RHead2: 
RHead3: 
RCTA:  Enroll !

ph_number: +91-6362315334
github_username: linkedin/company/quadralogics

footer: ©  2020  www.quadralogics.com , certifyme.online is a QuadraLogics concern 



# Build settings
markdown: kramdown


